/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.maestredam.qa.view;

import es.maestredam.qa.model.GestorInfo;
import es.maestredam.qa.model.Pregunta;
import es.maestredam.util.LinkedList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author franh
 */
public class DlgNewTestJuego extends javax.swing.JDialog {
    private GestorInfo gestor = new GestorInfo(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"/ProyectoPreguntasRespuestas/preguntas.dam");
    private Pregunta pregunta;
    private boolean seguir = true;
    private int contador = 0;
    private Set<Integer> numeros = new HashSet<>();
    LinkedList<Pregunta> preguntas = gestor.leerPreguntas();
    private int puntuacion;
    
    /**
     * Creates new form DlgNewTestJuego
     */
    public DlgNewTestJuego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnGroup.add(radioBtn1);
        btnGroup.add(radioBtn2);
        btnGroup.add(radioBtn3);
        setLocationRelativeTo(parent);
        getPregunta();
    }
    
    private void getPregunta(){
        int random;
        boolean diferente = false;
        if (seguir && contador<10){
            while (!diferente){
                random = (int) (Math.random()*(preguntas.size()));
                if (!numeros.contains(random) && seguir){
                    numeros.add(random);
                    pregunta = preguntas.get(random);
                    setPregunta();
                    diferente = true;
                }
            }
        }
        else if (contador==10){
            puntuacion = Integer.parseInt(txtPuntuacion.getText());
            dispose();
        }
    }
    
    private void setPregunta(){
        txtEnunciado.setText(pregunta.getEnunciado());
        if (pregunta.getRespuestaB()==null){
            radioBtn1.setVisible(false);
            radioBtn2.setVisible(false);
            radioBtn3.setVisible(false);
            txtRespuesta.setText("");
            txtRespuesta.setVisible(true);
            lblRespuesta.setVisible(true);
        }
        else{
            txtRespuesta.setVisible(false);
            lblRespuesta.setVisible(false);
            radioBtn1.setVisible(true);
            radioBtn2.setVisible(true);
            radioBtn3.setVisible(true);
            radioBtn1.setSelected(false);
            radioBtn2.setSelected(false);
            radioBtn3.setSelected(false);
            radioBtn1.setText(pregunta.getRespuestaA());
            radioBtn2.setText(pregunta.getRespuestaB());
            radioBtn3.setText(pregunta.getRespuestaC());
        }
        seguir = false;
    }
    
    public int getPuntuacion(){
        return puntuacion;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        txtEnunciado = new javax.swing.JTextField();
        radioBtn1 = new javax.swing.JRadioButton();
        radioBtn2 = new javax.swing.JRadioButton();
        radioBtn3 = new javax.swing.JRadioButton();
        lblEnunciado = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        txtRespuesta.setVisible(false);
        lblRespuesta = new javax.swing.JLabel();
        lblRespuesta.setVisible(false);
        btnAceptar = new javax.swing.JButton();
        txtPuntuacion = new javax.swing.JTextField();
        lblPuntuacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setText("Pregunta");

        lblEnunciado.setText("Enunciado:");

        lblRespuesta.setText("Respuesta:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblPuntuacion.setText("Puntuación:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(lblTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBtn2)
                                    .addComponent(radioBtn1)
                                    .addComponent(radioBtn3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(btnAceptar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnunciado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnunciado)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 169, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblRespuesta)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblPuntuacion)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lblTitulo)
                .addGap(54, 54, 54)
                .addComponent(lblEnunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioBtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtn3)
                        .addGap(18, 18, 18)
                        .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRespuesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(txtPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuntuacion))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        seguir = true;
        int extraida;
        contador++;
        if (pregunta.getRespuestaB()==null){
            if (pregunta.corregirCorta(txtRespuesta.getText(), pregunta) == true){
                puntuacion = Integer.parseInt(txtPuntuacion.getText());
                puntuacion++;
                txtPuntuacion.setText(" "+puntuacion);
            }
        }
        else{
            if (radioBtn1.isSelected()){
                if (pregunta.corregirTest(radioBtn1.getText(), pregunta)){
                    puntuacion = Integer.parseInt(txtPuntuacion.getText());
                    puntuacion+=1;
                    txtPuntuacion.setText(" "+puntuacion);
                }
            }
            else if (radioBtn2.isSelected()){
                if (pregunta.corregirTest(radioBtn2.getText(), pregunta)){
                    puntuacion = Integer.parseInt(txtPuntuacion.getText());
                    puntuacion+=1;
                    txtPuntuacion.setText(" "+puntuacion);
                }
            }
            else if (radioBtn3.isSelected()){
                if (pregunta.corregirTest(radioBtn3.getText(), pregunta)){
                    puntuacion = Integer.parseInt(txtPuntuacion.getText());
                    puntuacion+=1;
                    txtPuntuacion.setText(" "+puntuacion);
                }
            }
        }
        extraida = (pregunta.getCuentaExt())+1;
        gestor.guardarListaPreguntas(preguntas, false);
        getPregunta();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgNewTestJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgNewTestJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgNewTestJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgNewTestJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgNewTestJuego dialog = new DlgNewTestJuego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel lblEnunciado;
    private javax.swing.JLabel lblPuntuacion;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton radioBtn1;
    private javax.swing.JRadioButton radioBtn2;
    private javax.swing.JRadioButton radioBtn3;
    private javax.swing.JTextField txtEnunciado;
    private javax.swing.JTextField txtPuntuacion;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
